DROP TABLE IF EXISTS artists;

CREATE TABLE artists(
  artist_id INTEGER PRIMARY KEY generated by default as identity,
  artist_name VARCHAR NOT NULL UNIQUE,
  birthday date NOT NULL,
  birthplace VARCHAR(30) NOT NULL,
  is_alive BOOLEAN  NOT NULL DEFAULT true
);